function [x, y] = remove_ghost_points(x, y, x_ref, y_ref, tolerance)
    
    [tracks]=weighted_nearest_neighbor3D(x_ref, x, x_ref, ...
        y_ref, y, y_ref, ...
        zeros(size(x_ref)), zeros(size(x)), zeros(size(x_ref)), ...
          zeros(size(x_ref)), zeros(size(x)),...
        zeros(size(x_ref)), zeros(size(x)),...
        [1,0,0], tolerance);
    
    x = tracks(:,2);
    y = tracks(:,4);

end